-- Hapus panduan absensi lama (jika ada) untuk menghindari duplikasi
DELETE FROM public.system_guides WHERE system_code = 'absensi';

-- Masukkan panduan absensi baru per role
INSERT INTO public.system_guides (system_code, category, title, content_html, sort_order) VALUES
-- KRU
('absensi', 'Absensi & Kehadiran', 'Cara Melakukan Absen Masuk & Keluar', '<p>Proses absensi dilakukan dengan menggunakan fitur pengenalan wajah dan deteksi lokasi (GPS). Pastikan Anda memberikan izin akses kamera dan lokasi pada browser (Google Chrome/Safari) Anda.</p><p><strong>1. Masuk ke Beranda</strong><br/>Di halaman utama (Beranda), sistem akan menyiapkan kamera dan memuat lokasi Anda di peta. Pastikan titik lokasi Anda berada di dalam radius outlet.</p><p><strong>2. Pindai Wajah</strong><br/>Posisikan wajah Anda di dalam bingkai kamera yang tersedia dengan pencahayaan yang cukup. Lepaskan masker atau kacamata gelap agar sistem dapat mengenali wajah Anda.</p><p><strong>3. Rekam Absensi</strong><br/>Pilih tombol <strong>Absen Masuk</strong> jika Anda baru datang, atau <strong>Absen Keluar</strong> jika shift Anda sudah selesai. Sistem akan memproses dan menampilkan pesan berhasil jika wajah dan lokasi Anda valid.</p>', 1),
('absensi', 'Kasbon & Cuti', 'Cara Mengajukan Cuti atau Kasbon', '<p>Anda dapat mengajukan permohonan Cuti atau Kasbon (Pinjaman) langsung melalui aplikasi.</p><p><strong>1. Buka Halaman Pengajuan</strong><br/>Pilih menu <strong>Cuti</strong> atau <strong>Kasbon</strong> di bagian bawah layar atau menu samping.</p><p><strong>2. Isi Formulir Permohonan</strong><br/>Klik tombol <strong>+ Buat Pengajuan Baru</strong>. Isi form dengan lengkap, seperti tanggal cuti, alasan, atau nominal uang jika Anda mengajukan kasbon. Pastikan alasan tertulis dengan jelas.</p><p><strong>3. Tunggu Persetujuan</strong><br/>Setelah dikirim, status permohonan Anda adalah "Menunggu Persetujuan". SPV atau Admin akan meninjau pengajuan tersebut. Anda bisa memantau perubahan statusnya secara berkala di halaman yang sama.</p>', 2),
('absensi', 'Checklist Harian', 'Mengisi Checklist Pekerjaan Harian', '<p>Checklist adalah daftar tugas yang wajib Anda kerjakan dan centang setiap hari.</p><p><strong>1. Lihat Tugas Anda</strong><br/>Pilih menu <strong>Checklist Harian</strong>. Anda akan melihat daftar tugas yang harus diselesaikan untuk shift Anda.</p><p><strong>2. Centang Tugas yang Selesai</strong><br/>Setiap kali Anda selesai melakukan suatu tugas, klik atau centang kotak di sebelah tugas tersebut. SPV dapat memantau secara langsung tugas mana saja yang sudah Anda selesaikan.</p>', 3),

-- SPV
('absensi', 'Manajemen Data Kru', 'Cara Mendaftarkan Wajah Kru (Enrollment)', '<p>Sebelum Kru bisa absen, wajah mereka wajib didaftarkan ke dalam sistem AI melalui fitur Enrollment.</p><p><strong>1. Masuk ke Menu Enroll</strong><br/>Buka halaman <strong>Enrollment Crew</strong>. Anda akan melihat daftar Kru yang bekerja di outlet Anda beserta status pendaftaran wajah mereka.</p><p><strong>2. Pindai Wajah Kru</strong><br/>Pilih Kru yang belum terdaftar. Arahkan kamera ke wajah Kru tersebut dalam kondisi pencahayaan yang terang dan posisi wajah lurus ke depan. Sistem akan mengambil beberapa sampel wajah.</p><p><strong>3. Simpan Data</strong><br/>Setelah persentase pengambilan data mencapai 100%, simpan data tersebut. Mulai saat ini, Kru bersangkutan sudah bisa menggunakan fitur absensi mandiri.</p>', 4),
('absensi', 'Pemantauan Absensi', 'Memantau Papan Kehadiran & Rekap', '<p>Sebagai SPV, Anda bertanggung jawab memantau kedisiplinan dan absensi tim.</p><p><strong>1. Papan Kehadiran (Live)</strong><br/>Menu <strong>Papan Kehadiran</strong> menampilkan siapa saja yang saat ini sedang berada di outlet (aktif shift) secara <em>real-time</em>, lengkap dengan jam masuk mereka dan foto absensi.</p><p><strong>2. Rekap & Riwayat</strong><br/>Gunakan menu <strong>Rekap & Riwayat</strong> untuk melihat catatan absensi di hari-hari sebelumnya. Anda dapat memfilter berdasarkan tanggal atau nama kru. Data ini sangat penting untuk perhitungan gaji dan bonus.</p>', 5),
('absensi', 'Pengaturan Sistem', 'Mengatur Jangkauan GPS & Toleransi Keterlambatan', '<p>Sistem absensi dilengkapi dengan perlindungan manipulasi lokasi (Fake GPS).</p><p><strong>1. Buka Pengaturan Absensi</strong><br/>Pada menu <strong>Pengaturan Absensi</strong>, Anda dapat menetapkan titik tengah koordinat (Latitude & Longitude) outlet Anda.</p><p><strong>2. Atur Radius dan Toleransi</strong><br/>Tentukan <strong>Radius Jarak (dalam meter)</strong>. Kru hanya dapat absen jika jarak mereka berada di dalam radius ini. Anda juga dapat menetapkan batas jam masuk (misalnya Shift Pagi jam 08:00) dan batas toleransi keterlambatan (misalnya 15 menit) sebelum sistem menandai kru tersebut terlambat.</p>', 6),
('absensi', 'Manajemen Tugas & Persetujuan', 'Memonitor Checklist dan Menyetujui Cuti/Kasbon', '<p><strong>1. Manajemen Checklist</strong><br/>Pada menu <strong>Manajemen Checklist</strong>, Anda dapat membuat daftar tugas baru dan menetapkan jadwal berlakunya. Di menu <strong>Monitor Checklist</strong>, Anda bisa melihat persentase tugas yang sudah diselesaikan oleh para Kru pada hari tersebut.</p><p><strong>2. Menyetujui Permohonan</strong><br/>Buka menu <strong>Cuti</strong> atau <strong>Kasbon</strong> untuk melihat daftar pengajuan masuk dari Kru. Klik pengajuan tersebut, tinjau alasannya, lalu tekan tombol <strong>Setujui</strong> atau <strong>Tolak</strong>. Keputusan Anda akan langsung terlihat oleh Kru di aplikasi mereka.</p>', 7);
